### ISSUE TITLE
You don't need to sync the folder .serverless

### ISSUE THREAD

**Issue by tobiasbenkner** [bhall2001/serverless-nextjs-github-ci-cd#22]
you don't need to go through the sync step if you specify the existing distribution-id in the serverless.yml. so you don't need to create an extra s3 bucket to sync the builds.

```
name: prod-your-site-name

prod-your-site-name:
  component: '@sls-next/serverless-component@latest'
  inputs:
    bucketName: prod-your-site-name-s3
    description: "Lambda@Edge for prod-your-site-name"
    name:
      defaultLambda: prod-your-site-name-lambda
      apiLambda: prod-your-site-name-lambda
    domain: ["prod-your-site-name", "bobhall.net"]
    publicDirectoryCache: true
    runtime:
      defaultLambda: "nodejs14.x"
      apiLambda: "nodejs14.x"
    cloudfront:
      distributionId: your-distribution-id # https://us-east-1.console.aws.amazon.com/cloudfront/
```
